# Generated by Django 4.1.3 on 2022-12-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=50)),
                ('service_interval_miles', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('prev_odometer', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=255)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
