# Generated by Django 4.1.3 on 2022-12-09 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance_records', '0002_rename_vehicle_id_maintenance_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
