# Generated by Django 4.1.3 on 2022-12-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('make', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('make_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make.make')),
            ],
        ),
    ]
