# Generated by Django 4.1.3 on 2022-12-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill_up_records', '0003_fillup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='mpg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
