# Generated by Django 4.1.3 on 2022-12-07 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('make', '0001_initial'),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=30)),
                ('vehicle_name', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_year', models.IntegerField()),
                ('active', models.BooleanField()),
                ('odometer', models.IntegerField()),
                ('make_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make.make')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
