# Generated by Django 4.1.3 on 2022-12-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make_id',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='model_id',
            new_name='model',
        ),
    ]
