# Generated by Django 4.1.3 on 2022-12-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_rename_vehicle_name_vehicle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='Red', max_length=30),
            preserve_default=False,
        ),
    ]
